-- MySQL Script generated by MySQL Workbench
-- sex 29 nov 2019 09:41:38 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema contas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema contas
-- -----------------------------------------------------
CREATE DATABASE contas;
USE `contas`;

-- -----------------------------------------------------
-- Table `contas`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contas`.`pessoas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contas`.`dividas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contas`.`dividas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  `mes` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `percentual_desconto` DOUBLE NOT NULL,
  `pessoas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pessoas_id`),
  CONSTRAINT `fk_dividas_pessoas`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `contas`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `contas`.`proventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contas`.`proventos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ano` INT NOT NULL,
  `mes` INT NOT NULL,
  `valor` DOUBLE NOT NULL,
  `imposto` DOUBLE NOT NULL,
  `pessoas_id` INT NOT NULL,
  PRIMARY KEY (`id`, `pessoas_id`),
  CONSTRAINT `fk_proventos_pessoas1`
    FOREIGN KEY (`pessoas_id`)
    REFERENCES `contas`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
